const GISCUS_DISCUSSION_NUMBERS = {
  "blog/2021-in-review": 73,
  "blog/2022-in-review": 90,
  "blog/2023-in-review": 101,
  "blog/2024-in-review": 115,
  "blog/2025-in-review": 126,
  "blog/about-async-functions": 65,
  "blog/always-provide-customer-value": 75,
  "blog/array-types-in-type-script": 98,
  "blog/automatic-query-invalidation-after-mutations": 105,
  "blog/avoiding-hydration-mismatches-with-use-sync-external-store": 103,
  "blog/avoiding-legacy-systems": 49,
  "blog/avoiding-use-effect-with-callback-refs": 83,
  "blog/beware-the-leaking-any": 72,
  "blog/breaking-react-querys-api-on-purpose": 94,
  "blog/building-type-safe-compound-components": 127,
  "blog/calling-java-script-from-type-script": 46,
  "blog/component-composition-is-great-btw": 110,
  "blog/concurrent-optimistic-updates-in-react-query": 117,
  "blog/context-inheritance-in-tan-stack-router": 122,
  "blog/creating-query-abstractions": 128,
  "blog/deriving-client-state-from-server-state": 121,
  "blog/designing-design-systems": 125,
  "blog/dont-over-use-state": 45,
  "blog/effective-react-query-keys": 64,
  "blog/exhaustive-matching-in-type-script": 43,
  "blog/flow-to-type-script-migration-journey": 53,
  "blog/hooks-dependencies-and-stale-closures": 80,
  "blog/how-can-i": 82,
  "blog/how-infinite-queries-work": 109,
  "blog/inside-react-query": 89,
  "blog/introducing-x-state-store": 108,
  "blog/leveraging-the-query-function-context": 71,
  "blog/mastering-mutations-in-react-query": 70,
  "blog/my-open-source-origin-story": 116,
  "blog/my-slow-retreat-from-twitter": 112,
  "blog/no-love-for-boolean-parameters": 56,
  "blog/offline-react-query": 76,
  "blog/omit-for-discriminated-unions-in-type-script": 124,
  "blog/on-naming-things": 52,
  "blog/optional-vs-undefined": 77,
  "blog/oss-feature-decision-tree": 93,
  "blog/pedantic-index-signatures-in-type-script-4-1": 42,
  "blog/placeholder-and-initial-data-in-react-query": 66,
  "blog/please-stop-using-barrel-files": 107,
  "blog/practical-react-query": 51,
  "blog/putting-props-to-use-state": 50,
  "blog/react-19-and-suspense-a-drama-in-3-acts": 106,
  "blog/react-query-and-forms": 79,
  "blog/react-query-and-react-context": 97,
  "blog/react-query-and-type-script": 62,
  "blog/react-query-api-design-lessons-learned": 111,
  "blog/react-query-as-a-state-manager": 67,
  "blog/react-query-data-transformations": 57,
  "blog/react-query-error-handling": 68,
  "blog/react-query-fa-qs": 81,
  "blog/react-query-meets-react-router": 84,
  "blog/react-query-render-optimizations": 59,
  "blog/react-query-selectors-supercharged": 120,
  "blog/react-query-the-bad-parts": 114,
  "blog/ref-callbacks-react-19-and-the-compiler": 113,
  "blog/refactor-impactfully": 87,
  "blog/refs-events-and-escape-hatches": 85,
  "blog/reliable-query-prefetching-with-tanstack-router": 134,
  "blog/road-to-refactoring": 74,
  "blog/seeding-the-query-cache": 86,
  "blog/simplifying-use-effect": 54,
  "blog/solving-conflicts-in-package-lock-json": 44,
  "blog/status-checks-in-react-query": 60,
  "blog/tan-stack-router-and-query": 131,
  "blog/test-ids-are-an-a11y-smell": 129,
  "blog/testing-react-query": 61,
  "blog/the-beauty-of-tan-stack-router": 118,
  "blog/the-power-of-const-assertions": 48,
  "blog/the-query-options-api": 102,
  "blog/the-uphill-battle-of-memoization": 99,
  "blog/the-useless-use-callback": 119,
  "blog/the-vertical-codebase": 130,
  "blog/things-to-know-about-use-state": 55,
  "blog/thinking-in-react-query": 96,
  "blog/tooltip-components-should-not-exist": 123,
  "blog/type-safe-react-query": 91,
  "blog/use-state-for-one-time-initializations": 58,
  "blog/use-state-vs-use-reducer": 69,
  "blog/use-urgency": 78,
  "blog/using-web-sockets-with-react-query": 63,
  "blog/why-i-dont-like-reduce": 47,
  "blog/why-react-isnt-dying": 92,
  "blog/why-you-want-react-query": 100,
  "blog/working-with-zustand": 88,
  "blog/you-might-not-need-react-query": 95,
  "blog/zustand-and-react-context": 104,
} as const satisfies Record<string, number>;

export function getGiscusDiscussionNumber(
  pathname: string,
): number | undefined {
  const key = pathname.replace(/^\/+|\/+$/g, "");

  return GISCUS_DISCUSSION_NUMBERS[
    key as keyof typeof GISCUS_DISCUSSION_NUMBERS
  ];
}
